### ISSUE TITLE
Filter unmoderated events

### ISSUE THREAD

**Issue by bvanderveen** [Shift2Bikes/shiftcal#101]
I noticed some kind of questionable content on the beta calendar that I might have expected would be moderated out. Is there a moderation process for the site? See for example the events on Friday July 22 and Saturday July 23.

Not sure, but I think the JSON feed doesn't currently filter by the `review` column, but the legacy calendar does. 

- https://github.com/Shift2Bikes/shiftcal/blob/Legacy/include/view.php#L334
- https://github.com/Shift2Bikes/shiftcal/blob/Legacy/admclobber.php#L70

**Comment by kirkendall** [comment]
The "review" column is all about Pedalpalooza.  We need to edit hundreds of
events before sending them to the printer, and the event submission
deadline is only a few days before the printer's deadline.  That would be a
lot of editing in a very short time span, especially since the editing can
involve back-and-forth email with the event organizer.  To ease this
problem, the old calendar (and new?) lets the Pedalpalooza crew edit events
BEFORE the event deadline.  The "review" column keeps track of the editing
state of each event.

Non-Pedalpalooza events aren't normally reviewed that way.

HOWEVER, the old calendar took steps to prevent robots from submitting fake
events.  When you submit an event in the old calendar, some JS code
computes a checksum which is included in the submission.  The server then
recomputes the checksum and complains if they don't match.  This way, a
robot could only add fake events if it emulates a full JS-capable browser,
which would be quite a feat.  I don't see where the new calendar does
anything like that, yet.

**Comment by bvanderveen** [comment]
Thanks for the heads up. What you explained about reviewing Pedalpalooza content makes a lot of sense in light of the physical printing process for that event. This answers my core question regarding whether events posted to the general calendar are subject to moderation. Since they aren't, then there isn't a flag to filter on, and so there isn't a difference between the legacy and new site, so I'll close this issue. Thank you.
