### ISSUE TITLE
Safari can't open shift2bikes.org/fun2

### ISSUE THREAD

**Issue by OneHwang** [Shift2Bikes/shiftcal#218]
I tried this morning to open http://www.shift2bikes.org/fun2/ . It worked in Firebox, but not in Safari. I saw this fatal error:

TypeError: container.getWebLink is not a function. (In 'container.getWebLink(value.weburl)', 'container.getWebLink' is undefined)

**Comment by carrythebanner** [comment]
What version of Safari and macOS? I just tried the latest (Safari 11.1 on macOS 10.13.4) and I didn't see any errors, visible on the page or in the console.

**Comment by OneHwang** [comment]
Safari Version 11.0.3 (12604.5.6.1.1) and macOS Sierra 10.12.6

**Comment by OneHwang** [comment]
The problem appears to be ephemeral. The fun2 site works now. Because I don't know why, the problem could come back.

**Comment by carrythebanner** [comment]
Thanks for the update; glad to hear it's working now. I looked over the code and I don't see anything unusual there. That `getWebLink` helper works very similarly to the `getMapLink` helper, which has been on the Fun cal for many months without (known) issues. 

My most plausible theory is that something may have been cached (or not). Eventually the cache went stale and it started working when everything was requested fresh. Since it's not occurring now and I can't find anything to change, I'll close this issue. But please reopen or file a new one if you see it again.
