### ISSUE TITLE
Getting the site running locally on Ubuntu/Linux

### ISSUE THREAD

**Issue by CorySpitzer** [Shift2Bikes/shiftcal#42]
I have Apache, Mysql, and PHP installed but it's not clear how to actually get the site up from there. If someone can help me get up and running I can document it and add it to the setup instructions.

**Comment by georgemandis** [comment]
Hey Cory!

We probably could flesh-out and streamline the installation process for sure, as well as make a few other things clearer.

Do you unzip the `includes.tgz` and load the database from `init.sql`?

The current installation instructions tell you to untar the `includes.tgz` file into the main web root folder, but that's not exactly correct and should be changed. If you do that there are going to be a bunch of new files that we don't want/need in the repo next time you try to make a commit, and the default setup expects that `includes/` folder to be in the folder above it.

I have my local repo setup so that `includes/` is above the main folder containing the rest of the calendar code which I've put in a `cal/` folder. This more closely simulates how the actual site is structured:

[www.shift2bikes.org/cal/](http://www.shift2bikes.org/cal/)

So this means I end up accessing the repo in my browser locally like this:

http://localhost/cal

Taking the example in the current installation instructions, assuming your web root is this:

`/library/webserver/documents`

Create *another* folder inside of that and call it `cal/`. In that folder put the contents of the repo. Move `includes.tgz` to the web root and untar it there so that that content lives at:

`/library/webserver/documents/includes`

You will still need to change the contents of `account.php` to connect to your database locally, but this should fix two problems:

- You won't have to change line 9 defining where the untarred includes files live, which currently you'd have to.
- You won't accidentally commit a bunch of unnecessary files to the repo.

Does that help a little? This is more like a stub for better installation instructions, but let me know if this gets the ball rolling. And once we do get the instructions written up... Let's take a look at Issue #40 and see if we can eventually further automate/streamline this :)

**Comment by fool** [comment]
Hey Cory, did this help you get up and running?  If not, let us know where you landed and we'll improve the installation instructions until everything is working for you

**Comment by OneHwang** [comment]
Thorough descriptions of how to setup are available [here](https://github.com/Shift2Bikes/shiftcal/wiki/in-depth-setup-instructions).
